### ISSUE TITLE
"The dll is not allowed to be included or could not be found." exception when building project

### ISSUE THREAD

**Issue by tungunity96** [exodrifter/unity-python#13]
Hi sir,
Thanks for sharing this awesome library, it works smoothly in the editor! 

However, when I tried to build the project (PC standalone in this case), I got this error which I could not understand why. It said "ArgumentException: The Assembly PresentationFramework is referenced by IronPython.Wpf ('Assets/Libs/Python/IronPython.2.7.9/lib/net45/IronPython.Wpf.dll'). But the dll is not allowed to be included or could not be found.", but I have this .dll file in my Assets folder already.

I set the Scripting Runtime Version to ".NET 4.x Equivalent" and Api Compatibility Level to ".NET 4.x".
I also tried to import IronPython from official website but still got the same error. Could you help me with this problem?

![capture](https://user-images.githubusercontent.com/45156873/49066686-85c11b80-f254-11e8-932c-4ad3ae0c38b8.PNG)

**Comment by exodrifter** [comment]
It's ma'am, not sir.

It looks like I forgot to include `Microsoft.Scripting.Metadata.dll`. IronPython doesn't come bundled with it, so it needs to be added in manually.

I've updated [0.3.1](https://github.com/exodrifter/unity-python/releases/tag/0.3.1) to include that DLL., so the builds should work now if you download that release. Let me know if it works or if you have any more problems!

**Comment by tungunity96** [comment]
Dear ma'am,
After importing the 0.3.1 version, the build works like a charm! Thank you so much, you have saved my life! If I have any other problems, I will ask you ASAP.
(p/s: I apologize for my unacceptable mistake, please forgive me and close this issue. Once again, thank you!)

**Comment by exodrifter** [comment]
Glad it worked! 👍
