### ISSUE TITLE
IronPython.dll But the dll is not allowed to be included or could not be found.

### ISSUE THREAD

**Issue by tommynanny** [exodrifter/unity-python#24]
Unity Version: 2019.1.0f2
Unity Python 0.4.1

I got error when tried to build to WebGL.
I got an error with "ArgumentException: The Assembly Mono.Posix is referenced by IronPython ('Assets/Python/IronPython-2.7.9/IronPython.dll'). But the dll is not allowed to be included or could not be found."

![image](https://user-images.githubusercontent.com/22390882/74411856-3986da80-4e0a-11ea-8417-60942735f4ef.png)

![image](https://user-images.githubusercontent.com/22390882/74411986-74890e00-4e0a-11ea-8462-78c7702682ed.png)

**Comment by exodrifter** [comment]
I don't know if `Mono.Posix` is supported in WebGL, but this seems to fix the issue:

Copy `Mono.Posix.dll` from your Unity installation, wherever that is installed. For example, `2019.1.0f2\Editor\Data\Mono\lib\mono\2.0`.

![image](https://user-images.githubusercontent.com/1592386/74698297-e96d9680-51c2-11ea-8aee-85bfdf36f2ea.png)

Add it to your project in a `Plugins` folder.

![image](https://user-images.githubusercontent.com/1592386/74698335-0a35ec00-51c3-11ea-868c-9ea190a9abef.png)

This should make the build succeed. Again, I would like to point out that I'm not sure if `Mono.Posix` is supported in WebGL, so you might run into more issues later depending on what kind of functions you call.

**Comment by tommynanny** [comment]
Thank you so much! It seems to work!
