### ISSUE TITLE
UnauthorisedAccessException in Android

### ISSUE THREAD

**Issue by darshitg** [exodrifter/unity-python#29]
Thank you for sharing this package. it works well on editor, but when i built it for android and run application in android device it gives. 
**"UnauthorisedAccessException: Access to path "/" is denied."**

it is strange because file is present at this path and i can read the file via readalltext. but it gives me error when i pass the same file path to **"ExecuteFile()"**

Thanks

**Comment by exodrifter** [comment]
I'm sorry, but it's very difficult for me to provide any help on this issue with the information you provided. There are a lot of possibilities I can think of that might be causing your problem, but I don't have a good idea of which one it might be. Can you provide a minimal example that reproduces the problem?

**Comment by exodrifter** [comment]
Hey, it's been more than a month with no responses, so I'm closing this issue for now. Feel free to re-open this issue if you still need help and can provide more information on your issue.
