### ISSUE TITLE
Update IronPython?

### ISSUE THREAD

**Issue by grimmdev** [exodrifter/unity-python#3]
I seen IronPython 3 supports NET 4.5 while IronPython 2 still supports NET 2.0, I think the latest version is 2.7.7 or 2.7.8?

**Comment by exodrifter** [comment]
Sure, I can take a look at updating IronPython tomorrow.

**Comment by exodrifter** [comment]
The IronPython DLLs target .NET 4.x, which the Unity Editor does not support (as of 2017.3.0f3, only .NET 3.5 or lower is supported). This means I can't do a simple update of the repository.

I'll have to see if I can compile the source into a dll that targets .NET 3.5 but I'm not sure when I'll have time.

**Comment by exodrifter** [comment]
Since IronPython 2.7.8 is still in beta, I've decided to update to the last non-beta version, 2.7.7
