### ISSUE TITLE
MissingMemberException: 'module' object has no attribute '_getframe'

### ISSUE THREAD

**Issue by Darth-Carrotpie** [exodrifter/unity-python#6]
When trying to import a python module 'requests'
I'm getting an error:
MissingMemberException: 'module' object has no attribute '_getframe'
IronPython.Runtime.Operations.PythonOps.ObjectGetAttribute (IronPython.Runtime.CodeContext context, System.Object o, System.String name) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython/Runtime/Operations/PythonOps.cs:1135)
IronPython.Runtime.Operations.ObjectOps.__getattribute__ (IronPython.Runtime.CodeContext context, System.Object self, System.String name) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython/Runtime/Operations/ObjectOps.cs:74)
IronPython.Runtime.PythonModule.__getattribute__ (IronPython.Runtime.CodeContext context, System.String name) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython/Runtime/PythonModule.cs:120)
IronPython.Runtime.Binding.PythonGetMemberBinder+PythonModuleDelegate.Target (System.Runtime.CompilerServices.CallSite site, System.Object self, IronPython.Runtime.CodeContext context) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython/Runtime/Binding/PythonGetMemberBinder.cs:476)
System.Dynamic.UpdateDelegates.UpdateAndExecute2[Object,CodeContext,Object] (System.Runtime.CompilerServices.CallSite site, System.Object arg0, IronPython.Runtime.CodeContext arg1) (at C:/Users/dpek/Desktop/ironpython2/Runtime/Microsoft.Scripting.Core/Actions/UpdateDelegates.Generated.cs:387)
IronPython.Compiler.Ast.DynamicGetMemberExpression+GetMemberInstruction.Run (Microsoft.Scripting.Interpreter.InterpretedFrame frame) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython/Compiler/Ast/DynamicGetMemberExpression.cs:119)
Microsoft.Scripting.Interpreter.Interpreter.Run (Microsoft.Scripting.Interpreter.InterpretedFrame frame) (at C:/Users/dpek/Desktop/ironpython2/Runtime/Microsoft.Dynamic/Interpreter/Interpreter.cs:126)

After searching for solution in IronPython, there's a common [answer ](https://stackoverflow.com/questions/6997832/ironpython-sys-getframe-not-found) that the option has to be enabled:
` var options = new Dictionary<string, object>();
options["Frames"] = true;
var engine = Python.CreateEngine(options);`       
But! With: _global::UnityPython.CreateEngine();_ > CreateEngine cannot get options argument.
Apparently this is fixed in IronPython 2.7.8 - Frames are enabled by default...
--
Any quick fix?

**Comment by Darth-Carrotpie** [comment]
A follow up:
When providing options, the import code still wont run, throwing an amazingly huge error "FormatException":

`FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
System.String.FormatHelper (System.Text.StringBuilder result, IFormatProvider provider, System.String format, System.Object[] args) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System/String.cs:1925)
System.Text.StringBuilder.AppendFormat (IFormatProvider provider, System.String format, System.Object[] args) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Text/StringBuilder.cs:534)
System.Text.StringBuilder.AppendFormat (System.String format, System.Object[] args) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Text/StringBuilder.cs:527)
IronPython.Modules.Asn1Object..ctor (System.String shortName, System.String longName, Int32 nid, System.Byte[] oid) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython.Modules/_ssl.cs:52)
IronPython.Modules.PythonSsl..cctor () (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython.Modules/_ssl.cs:92)
Rethrow as TypeInitializationException: An exception was thrown by the type initializer for IronPython.Modules.PythonSsl
System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (RuntimeTypeHandle type) (at /Users/builduser/buildslave/mono/build/mcs/class/corlib/System.Runtime.CompilerServices/RuntimeHelpers.cs:101)
IronPython.Runtime.PythonContext.CreateBuiltinModule (System.String name) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython/Runtime/PythonContext.cs:1205)
IronPython.Runtime.PythonContext.GetBuiltinModule (System.String name) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython/Runtime/PythonContext.cs:1186)
IronPython.Runtime.Importer.ImportBuiltin (IronPython.Runtime.CodeContext context, System.String name) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython/Runtime/Importer.cs:727)
IronPython.Runtime.Importer.ImportTopAbsolute (IronPython.Runtime.CodeContext context, System.String name) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython/Runtime/Importer.cs:635)
IronPython.Runtime.Importer.ImportModule (IronPython.Runtime.CodeContext context, System.Object globals, System.String modName, Boolean bottom, Int32 level) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython/Runtime/Importer.cs:280)
IronPython.Modules.Builtin.__import__ (IronPython.Runtime.CodeContext context, System.String name, System.Object globals, System.Object locals, System.Object fromlist, Int32 level) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython/Modules/Builtin.cs:108)
(wrapper dynamic-method) object:CallSite.Target (System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,IronPython.Runtime.CodeContext,object,string,IronPython.Runtime.PythonDictionary,IronPython.Runtime.PythonDictionary,IronPython.Runtime.PythonTuple)
IronPython.Runtime.Importer.ImportLightThrow (IronPython.Runtime.CodeContext context, System.String fullName, IronPython.Runtime.PythonTuple from, Int32 level) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython/Runtime/Importer.cs:64)
IronPython.Runtime.Operations.PythonOps.ImportTop (IronPython.Runtime.CodeContext context, System.String fullName, Int32 level) (at C:/Users/dpek/Desktop/ironpython2/Languages/IronPython/IronPython/Runtime/Operations/PythonOps.cs:1841)
Microsoft.Scripting.Interpreter.FuncCallInstruction`4[IronPython.Runtime.CodeContext,System.String,System.Int32,System.Object].Run (Microsoft.Scripting.Interpreter.InterpretedFrame frame) (at C:/Users/dpek/Desktop/ironpython2/Runtime/Microsoft.Dynamic/Interpreter/Instructions/CallInstruction.Generated.cs:740)
Microsoft.Scripting.Interpreter.Interpreter.Run (Microsoft.Scripting.Interpreter.InterpretedFrame frame) (at C:/Users/dpek/Desktop/ironpython2/Runtime/Microsoft.Dynamic/Interpreter/Interpreter.cs:126)`

code form example provided in this repo:
`using UnityEngine;
using IronPython.Hosting;
using System.Collections.Generic;
namespace Exodrifter.UnityPython.Examples
{
	public class PythonLibrary : MonoBehaviour
	{
		void Start()
		{
            var options = new Dictionary<string, object>();
            options["Frames"] = true;
            options["FullFrames"] = true;
            var engine = Python.CreateEngine(options);
			var scope = engine.CreateScope();

			// Add the python library path to the engine. Note that this will
			// not work for builds; you will need to manually place the python
			// library files in a place that your code can find it at runtime.
			var paths = engine.GetSearchPaths();
			paths.Add(Application.dataPath + "/unity-python-master/Lib");
			engine.SetSearchPaths (paths);

			string code = @"
import os
filename = os.path.abspath ('python scripts/test.txt')
import requests";

			var source = engine.CreateScriptSourceFromString(code);
			source.Execute(scope);

			Debug.Log(scope.GetVariable<string>("filename"));
		}
	}
}`

**Comment by Darth-Carrotpie** [comment]
From what I can see at a glance, both errors reference wrong path (it might be one of lib build location- "C:/Users/dpek/Desktop/ironpython2")

**Comment by Darth-Carrotpie** [comment]
Any chance of looking into it soon? Or should I not bother waiting..?

**Comment by exodrifter** [comment]
Dude, chill. It's like six in the morning here and I just started looking into it.

**Comment by Darth-Carrotpie** [comment]
Dude, I'm chill. By "soon", I obviously don't mean this minute...
It's just good to know if I should wait for a week, or I can start looking at other implementations. I've seen there's a couple in the asset store - with not the best ratings and people comment that import is broken there also... :(
Might be either IronPython issue, or they simply cannot properly configure paths.

**Comment by exodrifter** [comment]
I decided to try using the official IronPython DLLs since IronPython doesn't officially support <4.0 and Unity has experimental .NET 4.6 support now. Unfortunately, I get a different error when trying to import the requests module:

```
(System.Numerics.BigInteger x, System.Numerics.BigInteger y) (at <6e95101e82ea4feb8f6d4cc1271fa904>:0)
IronPython.Runtime.Operations.Int32Ops.LeftShift (System.Int32 x, System.Numerics.BigInteger y) (at <6e95101e82ea4feb8f6d4cc1271fa904>:0)
System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet] (System.Runtime.CompilerServices.CallSite site, T0 arg0, T1 arg1) (at <11c1c8f1ba1046b191f565f88728429e>:0)
Microsoft.Scripting.Interpreter.DynamicInstruction`3[T0,T1,TRet].Run (Microsoft.Scripting.Interpreter.InterpretedFrame frame) (at <344681103b454854bf549f493ce00237>:0)
Microsoft.Scripting.Interpreter.Interpreter.Run (Microsoft.Scripting.Interpreter.InterpretedFrame frame) (at <344681103b454854bf549f493ce00237>:0)
Microsoft.Scripting.Interpreter.LightLambda.Run8[T0,T1,T2,T3,T4,T5,T6,T7,TRet] (T0 arg0, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7) (at <344681103b454854bf549f493ce00237>:0)
IronPython.Compiler.PythonCallTargets.OriginalCallTarget7 (IronPython.Runtime.PythonFunction function, System.Object arg0, System.Object arg1, System.Object arg2, System.Object arg3, System.Object arg4, System.Object arg5, System.Object arg6) (at <6e95101e82ea4feb8f6d4cc1271fa904>:0)
...
```
It seems like there's another bug in IronPython 2.7.8 somewhere or there's something else I don't know about. I don't know how to fix this issue, but I'll leave it open in case someone can figure this out or if a new version of IronPython works.

In the meantime, I've updated the project to IronPython 2.7.8 and I've also changed UnityPython.CreateEngine to accept an optional options parameter.

**Comment by exodrifter** [comment]
Hey, I took another look at this issue and it seems to work now. I'm not really sure what I was doing wrong at first, but these steps work:

1. Install Python 2.7.8
2. Use `pip` to install `requests`
3. Copy all of the newly installed packages from the `C:\Python27\Lib\site-packages` folder to `Assets/Python/Lib/` (or where ever you installed unity-python)
4. `import requests` works!

Let me know if you have any other related issues.

**Comment by exodrifter** [comment]
It's been more than a month (actually, much, much longer than that). I hope it's working for you now, but I'm closing this for now. If you need any more help with this issue, please feel free to re-open this.
