### ISSUE TITLE
using cv2 module occured "SyntaxErrorException: unexpected indent" Error.

### ISSUE THREAD

**Issue by IdolMenendez** [exodrifter/unity-python#9]
Hi,Thank you for this project.
Here is the issue:
I want to use opencv - python to do a little test in unity (to read a texture pixel debug),And I refer to the issue which you answered.

I move the "..Python/Lib/site-packages/cv2" file to my "Assets/Python/lib" Unity Folder.And the picture "is.png" is also under the "Assets/Python/lib" folder too. So I run my code which is worked good on PC python environment. And I got this :"SyntaxErrorException: unexpected indent". 

So now I can't to deal with it. So much appreciate if you can help.  👍

**Comment by IdolMenendez** [comment]
emmm. here is my code.

public class UsingPythonLib : MonoBehaviour
{

    void Start()
    {
        var engine = UnityPython.CreateEngine();
        var scope = engine.CreateScope();
        var paths = engine.GetSearchPaths();
        paths.Add(Application.dataPath + "/Python/lib");
        engine.SetSearchPaths(paths);

        string code = @"import cv2

						filename = 'is.png'
						result = cv2.imread(filename)
                        m_str = result[0][0][0]
						";

		var source = engine.CreateScriptSourceFromString(code);
		source.Execute(scope);
		Debug.Log(scope.GetVariable<string>("m_str"));
    }
}

**Comment by exodrifter** [comment]
Which issue are you referring to?

Your exception is thrown because the string you are passing looks like this:
```python
import cv2

					filename = 'is.png'
					result = cv2.imread(filename)
                    m_str = result[0][0][0]
```

I would suggest reading more about the [verbatim identifier](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/verbatim).

Also, I'd like to mention that it would be a lot easier to read and debug your python code if you placed it in a file and loaded it instead of putting it in a C# string.

**Comment by IdolMenendez** [comment]
Thanks for the answer.
I refer to the second issuse "MissingMemberException" 's answer.Here is your final reply:

Hey, I took another look at this issue and it seems to work now. I'm not really sure what I was doing wrong at first, but these steps work:

Install Python 2.7.8
Use pip to install requests
Copy the folders certifi, chardet, idna, requests, setuptools, and urllib3 from the C:\Python27\Lib\site-packages folder to Assets/Python/Lib/ (or where ever you installed unity-python)
import requests works!
Let me know if you have any other related issues.

I'm not quite sure the influence of the python version.So I move my Python/Lib/site-packages/cv2 folder below the Unity folder "Assets/Python/lib",and did a "import cv2"  operation.

This time I put the python script under a special folder.and I found another question."No module named cv2" .In general case,What I need to do is "pip install opencv - python",but I'm stuck in Unity....

my python Code  is:

import cv2

result = cv2.imread('sampleTexture.png')
m_str = str(result[0][0][0])

And C# Code is  :

public class UsingPythonLib : MonoBehaviour
{

    void Start()
    {
        ReadScriptFromFile();
    }


    void ReadScriptFromFile()
    {
        var engine = UnityPython.CreateEngine();
        var scope = engine.CreateScope();

        var paths = engine.GetSearchPaths();
        paths.Add(Application.dataPath + "/Python/lib/");
        var source = engine.CreateScriptSourceFromFile("Assets/PythonScript/cvSample.py");
        source.Execute(scope);
        Debug.Log(scope.GetVariable<string>("m_str"));
    }
}

Is anything wrong with my way to call the unity-python framework or I should just install python2.7.8 and move the cv2 folder to my Unity lib. A little bit confused...

**Comment by exodrifter** [comment]
If you don't call `SetSearchPaths`, then the search path won't actually be edited.

This is how you set the search path properly:
```
var paths = engine.GetSearchPaths();
paths.Add(Application.dataPath + "/Python/lib/");
engine.SetSearchPaths(paths);
```

Note that editing the `paths` variable doesn't do anything until you actually call `SetSearchPaths`.

**Comment by exodrifter** [comment]
Closing since there hasn't been a response in a while.
